// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // The single source of the connection string for every CLI command.
    // Prisma strips the `url` line out of the schema when a config supplies
    // one, so this is not a duplicate of it — it is the only copy.
    //
    // It was hardcoded to "file:./dev.db", which silently overrode
    // env("DATABASE_URL"). Reading the environment first is what lets the
    // integration suite point the CLI at a throwaway test.db; dotenv above
    // fills it in from .env for normal use, and does not override a value
    // that is already set.
    url: process.env.DATABASE_URL ?? "file:./dev.db",
  },
});
