// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Was hardcoded to "file:./dev.db", which silently overrode
    // env("DATABASE_URL") for every CLI command — including the ones the
    // integration suite runs against a throwaway test.db. Honouring the
    // environment first is what keeps tests off the dev database.
    url: process.env.DATABASE_URL ?? "file:./dev.db",
  },
});
